"""RBS category vocabulary, and the stopwords that make lexical matching useful.

This file is deliberately separate from the scoring engine. It is the part that gets
tuned against a real register, repeatedly, by someone who knows the taxonomy. Tuning it
should never require reading or re-testing ``mapping_suggest``.

Keys are matched against the RBS *category* — by code first, then by a substring of the
category name, lowercased. Name matching is the fallback so the lexicon keeps working on
a register whose CCC codes differ from the ones assumed here.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# stopwords
# --------------------------------------------------------------------------- #

#: Generic English plus schedule filler. Words that appear on a third of a P6 file carry
#: no signal — "install" does, "phase" does not. Deliberately short: an aggressive
#: stoplist silently deletes the vocabulary of whole disciplines.
STOPWORDS: frozenset[str] = frozenset(
    {
        # english
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "has",
        "have",
        "in",
        "is",
        "it",
        "its",
        "of",
        "on",
        "or",
        "that",
        "the",
        "to",
        "was",
        "were",
        "will",
        "with",
        "not",
        "no",
        "any",
        "all",
        "if",
        "into",
        "onto",
        "per",
        "via",
        # schedule filler
        "activity",
        "task",
        "phase",
        "stage",
        "step",
        "item",
        "work",
        "works",
        "misc",
        "miscellaneous",
        "general",
        "other",
        "various",
        "tbd",
        "tba",
        "na",
        "nil",
        "start",
        "finish",
        "begin",
        "end",
        "complete",
        "completion",
        "ongoing",
        "milestone",
        "summary",
        "total",
        "subtotal",
        "level",
        "wbs",
        "loe",
        "week",
        "weeks",
        "month",
        "months",
        "day",
        "days",
        "year",
        "years",
        "num",
        "number",
        "part",
        "section",
        "area",
        "zone",
        "unit",
        "package",
        # risk-register filler: these appear in nearly every cause/consequence field
        "risk",
        "issue",
        "impact",
        "impacts",
        "cause",
        "causes",
        "consequence",
        "consequences",
        "may",
        "could",
        "might",
        "result",
        "results",
        "resulting",
        "due",
        "lead",
        "leads",
        "leading",
        "potential",
        "possible",
        "likely",
        "delay",
        "delays",
        "delayed",
        "cost",
        "costs",
        "increase",
        "increased",
        "additional",
        "further",
        "significant",
        "project",
    }
)

# --------------------------------------------------------------------------- #
# category vocabulary
# --------------------------------------------------------------------------- #

#: Category code (CCC) -> schedule vocabulary. Extend freely; unknown codes simply score
#: zero on this signal rather than failing.
CATEGORY_TERMS: dict[str, tuple[str, ...]] = {
    "ENV": (
        "environmental",
        "environment",
        "permit",
        "approval",
        "assessment",
        "ea",
        "remediation",
        "contamination",
        "contaminated",
        "spill",
        "species",
        "habitat",
        "wetland",
        "archaeological",
        "archaeology",
        "heritage",
        "noise",
        "emission",
        "discharge",
        "monitoring",
        "baseline",
        "survey",
    ),
    "REG": (
        "permit",
        "permits",
        "permitting",
        "approval",
        "approvals",
        "licence",
        "license",
        "regulatory",
        "regulator",
        "authority",
        "authorization",
        "consent",
        "compliance",
        "inspection",
        "certification",
        "certificate",
        "code",
        "bylaw",
        "zoning",
        "variance",
        "submission",
        "review",
        "resubmission",
    ),
    "ENG": (
        "design",
        "engineering",
        "drawing",
        "drawings",
        "ifc",
        "ifr",
        "specification",
        "spec",
        "calculation",
        "model",
        "modelling",
        "study",
        "analysis",
        "detail",
        "detailed",
        "preliminary",
        "concept",
        "basis",
        "fee",
        "feed",
        "revision",
        "stamp",
        "sealed",
        "issued",
        "construction",
    ),
    "PRC": (
        "procurement",
        "tender",
        "bid",
        "rfp",
        "rfq",
        "award",
        "contract",
        "purchase",
        "po",
        "order",
        "vendor",
        "supplier",
        "subcontract",
        "subcontractor",
        "fabrication",
        "fabricate",
        "manufacture",
        "manufacturing",
        "delivery",
        "deliver",
        "lead",
        "shipment",
        "shipping",
        "freight",
        "expedite",
        "material",
        "materials",
        "equipment",
        "procure",
        "supply",
    ),
    "CON": (
        "construction",
        "construct",
        "install",
        "installation",
        "erect",
        "erection",
        "excavation",
        "excavate",
        "backfill",
        "concrete",
        "pour",
        "formwork",
        "rebar",
        "steel",
        "structural",
        "piling",
        "pile",
        "foundation",
        "grading",
        "paving",
        "mechanical",
        "electrical",
        "piping",
        "pipe",
        "weld",
        "welding",
        "civil",
        "demolition",
        "demolish",
        "mobilize",
        "mobilization",
        "site",
        "field",
    ),
    "COM": (
        "commissioning",
        "commission",
        "startup",
        "start-up",
        "testing",
        "test",
        "precommissioning",
        "handover",
        "turnover",
        "punch",
        "punchlist",
        "acceptance",
        "performance",
        "loop",
        "energization",
        "energize",
        "flush",
        "flushing",
        "hydrotest",
        "calibration",
        "training",
        "documentation",
        "closeout",
    ),
    "GEO": (
        "geotechnical",
        "geotech",
        "soil",
        "soils",
        "rock",
        "bedrock",
        "groundwater",
        "dewatering",
        "borehole",
        "investigation",
        "subsurface",
        "settlement",
        "excavation",
        "shoring",
        "slope",
        "foundation",
        "piling",
        "pile",
    ),
    "STK": (
        "stakeholder",
        "consultation",
        "engagement",
        "community",
        "public",
        "indigenous",
        "landowner",
        "easement",
        "acquisition",
        "expropriation",
        "access",
        "agreement",
        "notification",
        "hearing",
        "meeting",
        "municipal",
        "utility",
        "relocation",
        "crossing",
        "railway",
        "highway",
    ),
    "ORG": (
        "resource",
        "resourcing",
        "staffing",
        "crew",
        "labour",
        "labor",
        "mobilize",
        "mobilization",
        "demobilization",
        "training",
        "onboarding",
        "shift",
        "overtime",
        "productivity",
        "supervision",
        "management",
        "coordination",
        "interface",
        "handoff",
        "approval",
        "decision",
        "gate",
        "review",
    ),
    "EXT": (
        "weather",
        "winter",
        "freeze",
        "freezing",
        "thaw",
        "spring",
        "seasonal",
        "shutdown",
        "outage",
        "window",
        "restriction",
        "curfew",
        "strike",
        "labour",
        "labor",
        "market",
        "escalation",
        "currency",
        "border",
        "customs",
        "import",
        "logistics",
        "transport",
        "road",
        "haul",
    ),
}

#: Fallback when the CCC code is unrecognised: match on words in the category *name*.
#: Keeps the signal alive on a register with a different coding scheme.
NAME_HINTS: tuple[tuple[str, str], ...] = (
    ("environ", "ENV"),
    ("regulat", "REG"),
    ("permit", "REG"),
    ("engineer", "ENG"),
    ("design", "ENG"),
    ("procure", "PRC"),
    ("supply", "PRC"),
    ("contract", "PRC"),
    ("construct", "CON"),
    ("execution", "CON"),
    ("commission", "COM"),
    ("start-up", "COM"),
    ("startup", "COM"),
    ("geotech", "GEO"),
    ("ground", "GEO"),
    ("stakeholder", "STK"),
    ("community", "STK"),
    ("land", "STK"),
    ("organis", "ORG"),
    ("organiz", "ORG"),
    ("resource", "ORG"),
    ("external", "EXT"),
    ("market", "EXT"),
    ("weather", "EXT"),
)


def terms_for_category(code: str | None, name: str | None) -> frozenset[str]:
    """Schedule vocabulary for an RBS category. Empty when nothing matches.

    An empty result is not an error — it means this signal abstains for that category,
    and ``mapping_suggest`` redistributes its weight rather than scoring everything low.
    """
    if code:
        hit = CATEGORY_TERMS.get(code.strip().upper())
        if hit:
            return frozenset(hit)

    lowered = (name or "").lower()
    for needle, mapped in NAME_HINTS:
        if needle in lowered:
            return frozenset(CATEGORY_TERMS.get(mapped, ()))
    return frozenset()
