"""portfolio / program / project hierarchy, and everything existing moved into it

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-01

One node table for all three levels, and a scope foreign key on the three tables that own
authored work: ``risk``, ``schedule_file`` and ``simulation_run``. ``schedule_version``
and everything below it reach their scope through ``schedule_file.id``; mappings and
quantitative estimates reach it through ``risk.id``. One owner per artefact, no
denormalised copy to drift.

The backfill is the whole reason this is a hand-written migration rather than an
autogenerated one. Every existing row belongs to *something*, and the something is the
project that has been implicitly assumed since the first commit. It is created here, named
after the schedule already loaded where there is exactly one, and every existing row is
moved into it before the column is made non-nullable. There is no state in which a row
exists without a scope.

Two constraint changes on ``risk`` ride along, and they are not incidental: the register's
sequence and its code become unique *per scope*, so a second project's first environmental
risk is ENV-030-0001 rather than whatever number the first project had reached. Rewriting
this later would mean renumbering live registers.

``op.batch_alter_table`` throughout. SQLite cannot add a non-nullable column, drop a
table-level unique constraint, or add a foreign key in place; batch mode rebuilds the
table. Postgres executes the same operations directly. The suite runs on SQLite and
production is Postgres, so a migration that only works on one of them is a migration that
is only tested on one of them.
"""

import sqlalchemy as sa

from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


SCOPED = ("risk", "schedule_file", "simulation_run")


#: Name the backfill project after the schedule already loaded, where there is exactly
#: one. A user opening the tree for the first time should recognise what is in it; falling
#: back to a generic name is fine, and guessing wrong when two schedules disagree is not.
#:
#: Expressed as SQL rather than as a Python lookup so the whole migration stays
#: offline-renderable — ``alembic upgrade --sql`` cannot run a query and read its result,
#: and a data migration that only exists at runtime is one nobody can review before it
#: touches a production register.
_DEFAULT_NAME_SQL = """
    CASE WHEN (SELECT COUNT(DISTINCT project_name) FROM schedule_version) = 1
         THEN (SELECT MIN(project_name) FROM schedule_version)
         ELSE 'Project'
    END
"""


def upgrade() -> None:
    op.create_table(
        "scope_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        # Nullable and unique, not boolean and unique: many nulls are permitted in a
        # unique column and exactly one true is not, so "at most one default" becomes a
        # constraint the database keeps rather than a rule the application remembers.
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by", sa.String(length=120), nullable=False, server_default="Unknown"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["scope_node.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_scope_node_code"),
        sa.UniqueConstraint("is_default", name="uq_scope_node_is_default"),
    )
    op.create_index("ix_scope_node_kind", "scope_node", ["kind"])
    op.create_index("ix_scope_node_parent_id", "scope_node", ["parent_id"])

    op.execute(
        "INSERT INTO scope_node "
        "(kind, parent_id, name, is_default, sort_order, created_by) "
        f"SELECT 'project', NULL, {_DEFAULT_NAME_SQL}, TRUE, 0, 'system'"
    )

    # Nullable, backfilled, then tightened. Adding the column non-nullable in one step
    # fails on any database that already has rows, which is every database this runs
    # against that matters. The id is fetched by subquery rather than by reading one back,
    # for the offline-rendering reason above.
    for table in SCOPED:
        op.add_column(table, sa.Column("scope_id", sa.Integer(), nullable=True))
        op.execute(  # noqa: S608 - table names are the fixed tuple above
            f"UPDATE {table} SET scope_id = "
            "(SELECT id FROM scope_node WHERE is_default = TRUE)"
        )

    with op.batch_alter_table("risk") as batch:
        batch.alter_column("scope_id", existing_type=sa.Integer(), nullable=False)
        batch.drop_constraint("uq_risk_subcategory_seq", type_="unique")
        batch.create_foreign_key(
            "fk_risk_scope_id", "scope_node", ["scope_id"], ["id"], ondelete="RESTRICT"
        )
        batch.create_unique_constraint(
            "uq_risk_scope_subcategory_seq", ["scope_id", "subcategory_id", "seq"]
        )
        batch.create_unique_constraint("uq_risk_scope_code", ["scope_id", "risk_code"])
    # The code index stops being unique: uniqueness is now the per-scope constraint above.
    op.drop_index("ix_risk_risk_code", table_name="risk")
    op.create_index("ix_risk_risk_code", "risk", ["risk_code"])
    op.create_index("ix_risk_scope_id", "risk", ["scope_id"])

    for table in ("schedule_file", "simulation_run"):
        with op.batch_alter_table(table) as batch:
            batch.alter_column("scope_id", existing_type=sa.Integer(), nullable=False)
            batch.create_foreign_key(
                f"fk_{table}_scope_id",
                "scope_node",
                ["scope_id"],
                ["id"],
                ondelete="RESTRICT",
            )
        op.create_index(f"ix_{table}_scope_id", table, ["scope_id"])


def downgrade() -> None:
    for table in ("simulation_run", "schedule_file"):
        op.drop_index(f"ix_{table}_scope_id", table_name=table)
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(f"fk_{table}_scope_id", type_="foreignkey")
            batch.drop_column("scope_id")

    op.drop_index("ix_risk_scope_id", table_name="risk")
    op.drop_index("ix_risk_risk_code", table_name="risk")
    with op.batch_alter_table("risk") as batch:
        batch.drop_constraint("uq_risk_scope_code", type_="unique")
        batch.drop_constraint("uq_risk_scope_subcategory_seq", type_="unique")
        batch.drop_constraint("fk_risk_scope_id", type_="foreignkey")
        batch.create_unique_constraint("uq_risk_subcategory_seq", ["subcategory_id", "seq"])
        batch.drop_column("scope_id")
    op.create_index("ix_risk_risk_code", "risk", ["risk_code"], unique=True)

    op.drop_index("ix_scope_node_parent_id", table_name="scope_node")
    op.drop_index("ix_scope_node_kind", table_name="scope_node")
    op.drop_table("scope_node")
